apiVersion: metalk8s.scality.com/v1alpha1
kind: MirrorConfig
metadata:
  labels:
    app.kubernetes.io/name: metalk8s-registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: mirrorconfig-sample
spec:
  registries:
    - prefix: docker.io
    - prefix: ghcr.io
    - prefix: quay.io
