//go:build !ignore_autogenerated

/*
Copyright 2025 Scality.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationSpec) DeepCopyInto(out *AuthenticationSpec) {
	*out = *in
	out.MTLS = in.MTLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationSpec.
func (in *AuthenticationSpec) DeepCopy() *AuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTLSAuthenticationSpec) DeepCopyInto(out *MTLSAuthenticationSpec) {
	*out = *in
	out.CASecretRef = in.CASecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTLSAuthenticationSpec.
func (in *MTLSAuthenticationSpec) DeepCopy() *MTLSAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(MTLSAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MirrorPropagationSpec) DeepCopyInto(out *MirrorPropagationSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IgnorePaths != nil {
		in, out := &in.IgnorePaths, &out.IgnorePaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MirrorPropagationSpec.
func (in *MirrorPropagationSpec) DeepCopy() *MirrorPropagationSpec {
	if in == nil {
		return nil
	}
	out := new(MirrorPropagationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSolutionArchiveStatus) DeepCopyInto(out *NodeSolutionArchiveStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSolutionArchiveStatus.
func (in *NodeSolutionArchiveStatus) DeepCopy() *NodeSolutionArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSolutionArchiveStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	out.Server = in.Server
	out.Agent = in.Agent
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessStatus) DeepCopyInto(out *ProcessStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessStatus.
func (in *ProcessStatus) DeepCopy() *ProcessStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Registry) DeepCopyInto(out *Registry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Registry.
func (in *Registry) DeepCopy() *Registry {
	if in == nil {
		return nil
	}
	out := new(Registry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Registry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryList) DeepCopyInto(out *RegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Registry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryList.
func (in *RegistryList) DeepCopy() *RegistryList {
	if in == nil {
		return nil
	}
	out := new(RegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryNodeAgentSpec) DeepCopyInto(out *RegistryNodeAgentSpec) {
	*out = *in
	in.CertificateIssuerRef.DeepCopyInto(&out.CertificateIssuerRef)
	out.Authentication = in.Authentication
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryNodeAgentSpec.
func (in *RegistryNodeAgentSpec) DeepCopy() *RegistryNodeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryNodeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryServerSpec) DeepCopyInto(out *RegistryServerSpec) {
	*out = *in
	in.CertificateIssuerRef.DeepCopyInto(&out.CertificateIssuerRef)
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryServerSpec.
func (in *RegistryServerSpec) DeepCopy() *RegistryServerSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistrySpec) DeepCopyInto(out *RegistrySpec) {
	*out = *in
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.ArchivesPath != nil {
		in, out := &in.ArchivesPath, &out.ArchivesPath
		*out = new(string)
		**out = **in
	}
	if in.SolutionsPath != nil {
		in, out := &in.SolutionsPath, &out.SolutionsPath
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Server.DeepCopyInto(&out.Server)
	in.Agent.DeepCopyInto(&out.Agent)
	if in.MirrorPropagation != nil {
		in, out := &in.MirrorPropagation, &out.MirrorPropagation
		*out = new(MirrorPropagationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistrySpec.
func (in *RegistrySpec) DeepCopy() *RegistrySpec {
	if in == nil {
		return nil
	}
	out := new(RegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryStatus) DeepCopyInto(out *RegistryStatus) {
	*out = *in
	if in.Available != nil {
		in, out := &in.Available, &out.Available
		*out = new(bool)
		**out = **in
	}
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = new(bool)
		**out = **in
	}
	if in.ServerAvailable != nil {
		in, out := &in.ServerAvailable, &out.ServerAvailable
		*out = new(bool)
		**out = **in
	}
	if in.ServerReady != nil {
		in, out := &in.ServerReady, &out.ServerReady
		*out = new(bool)
		**out = **in
	}
	if in.AgentAvailable != nil {
		in, out := &in.AgentAvailable, &out.AgentAvailable
		*out = new(bool)
		**out = **in
	}
	if in.AgentReady != nil {
		in, out := &in.AgentReady, &out.AgentReady
		*out = new(bool)
		**out = **in
	}
	if in.MirrorSyncAvailable != nil {
		in, out := &in.MirrorSyncAvailable, &out.MirrorSyncAvailable
		*out = new(bool)
		**out = **in
	}
	if in.MirrorSyncReady != nil {
		in, out := &in.MirrorSyncReady, &out.MirrorSyncReady
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int)
		**out = **in
	}
	if in.ReadyServerReplicas != nil {
		in, out := &in.ReadyServerReplicas, &out.ReadyServerReplicas
		*out = new(int)
		**out = **in
	}
	if in.ReadyAgentReplicas != nil {
		in, out := &in.ReadyAgentReplicas, &out.ReadyAgentReplicas
		*out = new(int)
		**out = **in
	}
	if in.SelectedNodes != nil {
		in, out := &in.SelectedNodes, &out.SelectedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeIPs != nil {
		in, out := &in.NodeIPs, &out.NodeIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusPerNode != nil {
		in, out := &in.StatusPerNode, &out.StatusPerNode
		*out = make(map[string]NodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryStatus.
func (in *RegistryStatus) DeepCopy() *RegistryStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionArchive) DeepCopyInto(out *SolutionArchive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionArchive.
func (in *SolutionArchive) DeepCopy() *SolutionArchive {
	if in == nil {
		return nil
	}
	out := new(SolutionArchive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolutionArchive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionArchiveList) DeepCopyInto(out *SolutionArchiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SolutionArchive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionArchiveList.
func (in *SolutionArchiveList) DeepCopy() *SolutionArchiveList {
	if in == nil {
		return nil
	}
	out := new(SolutionArchiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SolutionArchiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SolutionArchiveStatus) DeepCopyInto(out *SolutionArchiveStatus) {
	*out = *in
	if in.Served != nil {
		in, out := &in.Served, &out.Served
		*out = new(bool)
		**out = **in
	}
	if in.Replicated != nil {
		in, out := &in.Replicated, &out.Replicated
		*out = new(bool)
		**out = **in
	}
	if in.ServedReplicas != nil {
		in, out := &in.ServedReplicas, &out.ServedReplicas
		*out = new(int)
		**out = **in
	}
	if in.TargetReplicas != nil {
		in, out := &in.TargetReplicas, &out.TargetReplicas
		*out = new(int)
		**out = **in
	}
	if in.NodeSolutionArchives != nil {
		in, out := &in.NodeSolutionArchives, &out.NodeSolutionArchives
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StatusPerNodeSolutionArchive != nil {
		in, out := &in.StatusPerNodeSolutionArchive, &out.StatusPerNodeSolutionArchive
		*out = make(map[string]NodeSolutionArchiveStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SolutionArchiveStatus.
func (in *SolutionArchiveStatus) DeepCopy() *SolutionArchiveStatus {
	if in == nil {
		return nil
	}
	out := new(SolutionArchiveStatus)
	in.DeepCopyInto(out)
	return out
}
