name: "Post Merge"

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      is-development: false
      is-latest: true
      is-stable: false

  test-e2e:
    needs: build
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit
    with:
      image_with_tag: ${{ needs.build.outputs.image_tag }}
      full_suite: true
