name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Private Go Environment
        uses: ./.github/actions/setup-go
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Running Tests
        run: |
          go mod tidy
          make test
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
