name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Private Go Environment
        uses: ./.github/actions/setup-go
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Running Tests
        run: |
          go mod tidy
          make test
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
